kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 8888
    hostPort: 5555
    protocol: tcp
- role: worker
  extraPortMappings:
  - containerPort: 8888
    hostPort: 5556
    protocol: tcp
- role: worker
  extraPortMappings:
  - containerPort: 8888
    hostPort: 5557
    protocol: tcp